### ISSUE TITLE
image = imread(os.path.join(root, filename))[13:77, 35:99, :3]

### ISSUE THREAD

**Issue by daydayjump** [theeluwin/love2live#1]
Hello,when I run python preprocess.py, I always get the error:
`File "preprocess.py", line 77, in preprocess
    image = imread(os.path.join(root, filename))[13:77, 35:99, :3]
IndexError: too many indices for array
`
 I am quite new to pytorch so I do not have any idea about how to solve this. Any suggestion? A thanks in advance!

**Comment by theeluwin** [comment]
Not quite sure. Sorry about that. Check whether the loaded images (variable `image`) has proper type and shape. It should be a numpy nd-array with shape like `(?, ?, 4)` or `(?, ?, 3)`.

**Comment by daydayjump** [comment]
Thanks a lot. I find the loaded images was not downloaded completely. When I redownload the image, the error don't  happen.

**Comment by theeluwin** [comment]
Oh aha. Happy to hear that it's solved. Anyway, thank you for involving.
